name: Deploy CI4 to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploying to InfinityFree
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Sync files via FTP
        # Pastikan S dan K kapital di SamKirland
        uses: SamKirkland/ftp-deploy-action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /htdocs/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/tests/**
            **/writable/debugbar/**
            .env